# Generated by Django 2.0.1 on 2018-01-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosovatchats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosovatchat',
            name='skytuc',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cosovatchat',
            name='sokytuc',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cosovatchat',
            name='sphonghoc',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cosovatchat',
            name='sthuvien',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cosovatchat',
            name='svandong',
            field=models.FloatField(blank=0, default=0),
        ),
        migrations.AlterField(
            model_name='cosovatchat',
            name='tongdientich',
            field=models.FloatField(blank=0, default=0),
        ),
    ]
