# Generated by Django 2.0.1 on 2018-01-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosovatchats', '0002_auto_20180117_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosovatchat',
            name='skytuc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cosovatchat',
            name='sokytuc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cosovatchat',
            name='sphonghoc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cosovatchat',
            name='sthuvien',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cosovatchat',
            name='svandong',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cosovatchat',
            name='tongdientich',
            field=models.FloatField(default=0),
        ),
    ]
